### ISSUE TITLE
Images with root links are not displaying properly

### ISSUE THREAD

**Issue by bbringhu** [AdobeDocs/vsc-extensions#23]
Images with root links are not displaying properly in preview. Only images with relative links are displaying. Ctrl/Cmd-clicking a link with a root link appears to be dead. 

Examples: 

* This relative link works in preview: ![Files](assets/command-p.png)
* This root link is broken in preview: ![Files](/help/main-guide/assets/command-p.png)

CC: @geverit4 @end58763 - I think we forgot about this one, but it's important. If we can fix this now, it would be worth delaying the update to the storefront plugin. If it's more difficult, we can hold off.

**Comment by geverit4** [comment]
@bbringhu, I get "not found" when I click on https://github.com/AdobeDocs/vsc-extensions/issues/assets/command-p.png.  Is it a permission thing where I cannot see them?

I am able to see a problem in the relative link code - but it's related to having multiple folders in a VSC workspace.  So, I'm working that right now.

**Comment by bbringhu** [comment]
I'll re-create the issue in this repo...

**Comment by bbringhu** [comment]
@geverit4 - Open this file in VSC:

https://github.com/AdobeDocs/vsc-extensions/blob/master/link-test.md

**Comment by geverit4** [comment]
The problem here is related to the difference between a "workspace" and a "folder" in VSCode.  Currently, the pathfinder code doesn't make the distinction, so it works if you have a workspace open with multiple folders in it, but not if you just have the folder open directly. It's kind of messy to figure out what kind of folder structure any given file is dealing with.

**Comment by geverit4** [comment]
@bbringhu I should have been more clear that I expect to handle any arbitrary folder structure. So whether the folder is inside a workspace or opened by itself, I would expect those to be the common cases that would be handled. 

I *could* handle cases like opening VSCode on a folder deeper inside of the repo, but it seems like bad form to search for links above the current root level of the workspace, since that could easily cascade into walking a lot of trees irrelevant to the source file's repository.

**Comment by bbringhu** [comment]
We don't need to handle cases when any folder other than the repo folder is open in VSC. Let's assume that the user is editing files at the repo level.

**Comment by geverit4** [comment]
Fixed with issue #29
