### ISSUE TITLE
Unexpected errors: Markdown linting rules

### ISSUE THREAD

**Issue by jeff-matthews** [AdobeDocs/vsc-extensions#41]
The extension recently started identifying .md linting errors with lists:

> MD007/ul-indent: Unordered list indentation [Expected: 4; Actual: 2]markdownlint[MD007](https://github.com/DavidAnson/markdownlint/blob/v0.26.2/doc/Rules.md#md007)

The configuration that the extension is using for `MD007` doesn't seem to match the configuration that we're using in our production pipeline because these errors do not fail validation during the publication process. 

I'm not sure what the expected behavior is, but I assume that the extension configuration should match our production pipeline configuration.

Cc: @bbringhu 

![Screen Shot 2022-09-12 at 5 02 59 PM](https://user-images.githubusercontent.com/13662379/189973480-95b19780-a921-4d93-9075-89f229237bb2.png)

**Comment by bbringhu** [comment]
I don't get this error on one computer, but I do on another. Here's what the error looks like:

![Screenshot 2022-11-14 at 1 11 27 PM](https://user-images.githubusercontent.com/6193209/201766573-81b62314-3ef7-461b-adf7-69828ee5e7b2.png)

**Comment by hguthrie** [comment]
I noticed when I moved to my new laptop, I received different errors. I compared the `settings.json` file between computers.  I have the same extensions installed in VScode, but the files were different. I'm not sure why or how. But maybe that has something to do with it?
File is in ~/library/application support/code/user/setting.json

**Comment by geverit4** [comment]
Here is the test case I created to test this.  Please let me know if there are any other edge cases that need to be addressed:

# Issue 41 - Unexpected errors: Markdown linting rules

The extension recently started identifying .md linting errors with lists:

> MD007/ul-indent: Unordered list indentation [Expected: 4; Actual: 2]markdownlintMD007

The configuration that the extension is using for MD007 doesn't seem to match the configuration that we're using in our production pipeline because these errors do not fail validation during the publication process.

I'm not sure what the expected behavior is, but I assume that the extension configuration should match our production pipeline configuration.

The Adobe Flavored Markdown configuration for list-related warnings is:

```
    ...
    "MD007": {
      "indent": 4
    },
    ...
    "MD030": {
      "ul_multi": 3,
      "ol_multi": 2
    },
    ...
```

Example of nested list that fails MD007 and MD030 rules.

* This fails MD030 because it is followed by an indented list, but it only has one space after the asterisk.
  * This fails MD007 because it is indented with two spaces instead of four.

Example of non-nested bullet list that does not fail any rules:

* This does not fail MD030 because it is not followed by an indented list.
* This does not fail MD007 because it is not indented.

Example of a nested list that does not fail any rules:

*   This does not fail MD030 because it is followed by an indented list, and it has three spaces after the asterisk.
    * This does not fail MD007 because it is indented with four spaces.
    * This does not fail MD007 because it is indented with four spaces.
*   This does not fail MD030 because is in an indented list.

Example of a nested list that fails MD030 but not MD007:

* This fails MD030 and MD005 because it is followed by an indented list, but it only has two spaces after the asterisk.
    * This does not fail MD007 because it is indented with four spaces.
    * This does not fail MD007 because it is indented with four spaces.

Example of a nested list that fails MD007 but not MD030:

* This fails MD030 because it is followed by an indented list that fails MD007
 * This fails MD007 and MD005 because it is indented inconsistently with the previous list item.
 * This fails MD007 and MD005 because it is indented with two spaces instead of four.

**Comment by geverit4** [comment]
@hguthrie - I suspect this has to do with how the Markdown Extension would improperly overwrite the user settings with the default configuration values.  

Here is the current linting rules configuration:

```
{
    "line-length": false,
    "AM001": false,
    "AM009": false,
    "AM011": false,
    "MD003": {
      "style": "atx"
    },
    "MD004": {
      "style": "consistent"
    },
    "MD007": {
      "indent": 4
    },
    "MD009": false,
    "MD012": false,
    "MD014": false,
    "MD024": false,
    "MD025": {
      "front_matter_title": ""
    },
    "MD026": false,
    "MD027": false,
    "MD028": false,
    "MD030": {
      "ul_multi": 3,
      "ol_multi": 2
    },
    "MD033": {
      "allowed_elements": [
        "a",
        "b",
        "br",
        "caption",
        "code",
        "col",
        "colgroup",
        "div",
        "em",
        "I",
        "img",
        "li",
        "ol",
        "p",
        "pre",
        "s",
        "span",
        "strong",
        "sub",
        "sup",
        "table",
        "tbody",
        "td",
        "tfoot",
        "th",
        "thead",
        "tr",
        "u",
        "ul"
      ]
    },
    "MD036": false,
    "MD038": false,
    "MD039": false,
    "MD040": false,
    "MD045": false
};

```
